### ISSUE TITLE
Fetch plugin not working

### ISSUE THREAD

**Issue by shivani-hotstar** [Diogomrol/gocd-s3-artifact-plugin#15]
I have two pipelines .
Push artifact working fine but when my dependent pipeline trying to fetch the artifact from s3 bucket .
Giving me this error:-

[cd.go.artifact.s3] Retrieving file `xyz/abc/env.sh` from S3 bucket `xvz-us-west-1`.
[cd.go.artifact.s3] Failed pull source file: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: B99807E787B09977; S3 Extended Request ID: VwF4gBCo8v1vf7ITQ+4njuvq6+dWyY5sX5yKZ5X4umDmWSur3vrkznU2j86R7G3MvvaTbuNNl1o=), S3 Extended Request ID: VwF4gBCo8v1vf7ITQ+4njuvq6+dWyY5sX5yKZ5X4umDmWSur3vrkznU2j86R7G3MvvaTbuNNl1o=
The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed pull source file: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: B99807E787B09977; S3 Extended Request ID: VwF4gBCo8v1vf7ITQ+4njuvq6+dWyY5sX5yKZ5X4umDmWSur3vrkznU2j86R7G3MvvaTbuNNl1o=), S3 Extended Request ID: VwF4gBCo8v1vf7ITQ+4njuvq6+dWyY5sX5yKZ5X4umDmWSur3vrkznU2j86R7G3MvvaTbuNNl1o='

And the user which is integrated with gocd server has full s3 access.

**Comment by shivani-hotstar** [comment]
@Diogomrol hey can you help in this issue . Plugin working fine for single fine in current directory but when you trying to fetch the data from the sub-folders not working.

**Comment by tomzo** [comment]
@shivani-hotstar can you post the following information so that we can reproduce the bug in tests?
1. Paths of files that are on disk during the fetch.
2. The configuration of the upload part 
2. What was uploaded to AWS S3.
3. The configuration of fetch part.
3. The plugin version.

**Comment by shivani-hotstar** [comment]
1. Acc to json file should be fetch from 
```
{"s3extid":{"IsFile":true,"Destination":"xyz","Source":"terraform/env.sh"}}
```

2 configuration of the upload part:
```
      artifacts:
                  - build:
                      source: terraform/env.sh
                  - external:
                      id: s3extid
                      store_id: s3bucket
                      configuration:
                        options:
                          Destination: 'xyz'
                          Source: terraform/env.sh
```
3. I have one bucket abc which  has xyz folder and under this folder i have my env.sh file which i want to fetch .

4. fetch part configuration:
```
         tasks:
                  - fetch:
                      options:
                        SubPath: xyz
                        Destination: ''
                      artifact_id: s3extid
                      pipeline: "123-dub"
                      stage: terraform-deploy
                      job: deploy
                      artifact_origin: external
                      run_if: passed
```

5. 2.0.0/s3-artifact-plugin-2.0.0-42.jar .  


Error:-
```
[cd.go.artifact.s3] Retrieving file `xyz/terraform/env.sh` from S3 bucket `bucket_name`.
[cd.go.artifact.s3] Failed pull source file: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 93F7B05DBB835773; S3 Extended Request ID: en3/IJ2+B/Y4NjrWohzwWVUCHJmQ8W39PtOlJFT/cRzjmI2oNYZeTd6v4CvP8CARjg/Il2o0Y/k=), S3 Extended Request ID: en3/IJ2+B/Y4NjrWohzwWVUCHJmQ8W39PtOlJFT/cRzjmI2oNYZeTd6v4CvP8CARjg/Il2o0Y/k=
The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed pull source file: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 93F7B05DBB835773; S3 Extended Request ID: en3/IJ2+B/Y4NjrWohzwWVUCHJmQ8W39PtOlJFT/cRzjmI2oNYZeTd6v4CvP8CARjg/Il2o0Y/k=), S3 Extended Request ID: en3/IJ2+B/Y4NjrWohzwWVUCHJmQ8W39PtOlJFT/cRzjmI2oNYZeTd6v4CvP8CARjg/Il2o0Y/k='
[go] Task status: failed, took: 0.573s
```

**Comment by shivani-hotstar** [comment]
@tomzo @Diogomrol hey any findings?

**Comment by tomzo** [comment]
@shivani-hotstar thank you for submitting details. I didn't have time to debug this yet as I am a quite busy. I think your use case will suffice to fix it, I'll try to have a look at at, by the end of this week.

**Comment by tomzo** [comment]
@shivani-hotstar me and @sradnev have tried to reproduce the problems you are having using the details you provided. You can review the test cases we have added in https://github.com/Diogomrol/gocd-s3-artifact-plugin/commit/59a81d3ef51a22b3248f4ff593662121d880bffa

The tests are passing, including an e2e cases which both publish and fetch artifacts.

The 3 things that we noticed:
1:
In your upload definition, the `build` is not really necessary, since if you want to use external plugin for storage, you should need only 1 method for artifacts upload.
```
      artifacts:
                  - build:
                      source: terraform/env.sh
                  - external:
                      id: s3extid
                      store_id: s3bucket
                      configuration:
                        options:
                          Destination: 'xyz'
                          Source: terraform/env.sh
```

2: 

> I have one bucket abc which has xyz folder and under this folder i have my env.sh file which i want to fetch .

This seems inaccurate. With above configuration, the file that is being created on AWS is `xyz/terraform/env.sh`.

3: 
The `SubPath` is redundant and ignored in this case. You don't need to specify a subpath when artifact is just a single file.
```
fetch part configuration:

         tasks:
                  - fetch:
                      options:
                        SubPath: xyz
                        Destination: ''
                      artifact_id: s3extid
                      pipeline: "123-dub"
                      stage: terraform-deploy
                      job: deploy
                      artifact_origin: external
                      run_if: passed
```
